
// src/lib/quizData.ts
export interface QuizQuestion {
  id: number;
  question: string;
  options: {
    a: string;
    b: string;
    c: string;
    d: string;
  };
  answer: 'a' | 'b' | 'c' | 'd';
}

export const allQuizQuestions: QuizQuestion[] = [
  {
    id: 1,
    question: "Which stage of labor involves full cervical dilation?",
    options: { a: "First stage", b: "Second stage", c: "Third stage", d: "Latent stage" },
    answer: "b",
  },
  {
    id: 2,
    question: "Which is a common sign of labor?",
    options: { a: "Weight gain", b: "Breast tenderness", c: "Regular uterine contractions", d: "Increased appetite" },
    answer: "c",
  },
  {
    id: 3,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 4,
    question: "Which stage of labor involves full cervical dilation?",
    options: { a: "First stage", b: "Second stage", c: "Third stage", d: "Latent stage" },
    answer: "b",
  },
  {
    id: 5,
    question: "Which is a common sign of labor?",
    options: { a: "Weight gain", b: "Breast tenderness", c: "Regular uterine contractions", d: "Increased appetite" },
    answer: "c",
  },
  {
    id: 6,
    question: "Which hormone is primarily responsible for maintaining pregnancy?",
    options: { a: "Estrogen", b: "Progesterone", c: "Oxytocin", d: "Prolactin" },
    answer: "b",
  },
  {
    id: 7,
    question: "What is the normal fetal heart rate range?",
    options: { a: "110-160 bpm", b: "90-140 bpm", c: "120-170 bpm", d: "80-120 bpm" },
    answer: "a",
  },
  {
    id: 8,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 9,
    question: "What condition is characterized by high blood pressure and protein in the urine during pregnancy?",
    options: { a: "Eclampsia", b: "Gestational diabetes", c: "Preeclampsia", d: "Placenta previa" },
    answer: "c",
  },
  {
    id: 10,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 11,
    question: "Which vaccine is recommended during every pregnancy?",
    options: { a: "MMR", b: "Varicella", c: "Tdap", d: "Hepatitis B" },
    answer: "c",
  },
  {
    id: 12,
    question: "What is the normal fetal heart rate range?",
    options: { a: "110-160 bpm", b: "90-140 bpm", c: "120-170 bpm", d: "80-120 bpm" },
    answer: "a",
  },
  {
    id: 13,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 14,
    question: "Which vitamin is essential to prevent neural tube defects during pregnancy?",
    options: { a: "Vitamin A", b: "Vitamin B12", c: "Folic Acid", d: "Vitamin D" },
    answer: "c",
  },
  {
    id: 15,
    question: "Which vaccine is recommended during every pregnancy?",
    options: { a: "MMR", b: "Varicella", c: "Tdap", d: "Hepatitis B" },
    answer: "c",
  },
  {
    id: 16,
    question: "Which is a common sign of labor?",
    options: { a: "Weight gain", b: "Breast tenderness", c: "Regular uterine contractions", d: "Increased appetite" },
    answer: "c",
  },
  {
    id: 17,
    question: "What is the normal duration of human pregnancy?",
    options: { a: "38 weeks", b: "40 weeks", c: "42 weeks", d: "36 weeks" },
    answer: "b",
  },
  {
    id: 18,
    question: "Which vitamin is essential to prevent neural tube defects during pregnancy?",
    options: { a: "Vitamin A", b: "Vitamin B12", c: "Folic Acid", d: "Vitamin D" },
    answer: "c",
  },
  {
    id: 19,
    question: "What is the normal fetal heart rate range?",
    options: { a: "110-160 bpm", b: "90-140 bpm", c: "120-170 bpm", d: "80-120 bpm" },
    answer: "a",
  },
  {
    id: 20,
    question: "Which vaccine is recommended during every pregnancy?",
    options: { a: "MMR", b: "Varicella", c: "Tdap", d: "Hepatitis B" },
    answer: "c",
  },
  {
    id: 21,
    question: "What is the most common cause of postpartum hemorrhage?",
    options: { a: "Retained placenta", b: "Uterine atony", c: "Cervical tear", d: "Vaginal laceration" },
    answer: "b",
  },
  {
    id: 22,
    question: "Which stage of labor involves full cervical dilation?",
    options: { a: "First stage", b: "Second stage", c: "Third stage", d: "Latent stage" },
    answer: "b",
  },
  {
    id: 23,
    question: "What condition is characterized by high blood pressure and protein in the urine during pregnancy?",
    options: { a: "Eclampsia", b: "Gestational diabetes", c: "Preeclampsia", d: "Placenta previa" },
    answer: "c",
  },
  {
    id: 24,
    question: "What is the normal duration of human pregnancy?",
    options: { a: "38 weeks", b: "40 weeks", c: "42 weeks", d: "36 weeks" },
    answer: "b",
  },
  {
    id: 25,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 26,
    question: "Which hormone is primarily responsible for maintaining pregnancy?",
    options: { a: "Estrogen", b: "Progesterone", c: "Oxytocin", d: "Prolactin" },
    answer: "b",
  },
  {
    id: 27,
    question: "Which vaccine is recommended during every pregnancy?",
    options: { a: "MMR", b: "Varicella", c: "Tdap", d: "Hepatitis B" },
    answer: "c",
  },
  {
    id: 28,
    question: "What condition is characterized by high blood pressure and protein in the urine during pregnancy?",
    options: { a: "Eclampsia", b: "Gestational diabetes", c: "Preeclampsia", d: "Placenta previa" },
    answer: "c",
  },
  {
    id: 29,
    question: "Which vitamin is essential to prevent neural tube defects during pregnancy?",
    options: { a: "Vitamin A", b: "Vitamin B12", c: "Folic Acid", d: "Vitamin D" },
    answer: "c",
  },
  {
    id: 30,
    question: "Which vitamin is essential to prevent neural tube defects during pregnancy?",
    options: { a: "Vitamin A", b: "Vitamin B12", c: "Folic Acid", d: "Vitamin D" },
    answer: "c",
  },
  {
    id: 31,
    question: "Which hormone is primarily responsible for maintaining pregnancy?",
    options: { a: "Estrogen", b: "Progesterone", c: "Oxytocin", d: "Prolactin" },
    answer: "b",
  },
  {
    id: 32,
    question: "What is the normal duration of human pregnancy?",
    options: { a: "38 weeks", b: "40 weeks", c: "42 weeks", d: "36 weeks" },
    answer: "b",
  },
  {
    id: 33,
    question: "What condition is characterized by high blood pressure and protein in the urine during pregnancy?",
    options: { a: "Eclampsia", b: "Gestational diabetes", c: "Preeclampsia", d: "Placenta previa" },
    answer: "c",
  },
  {
    id: 34,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 35,
    question: "What condition is characterized by high blood pressure and protein in the urine during pregnancy?",
    options: { a: "Eclampsia", b: "Gestational diabetes", c: "Preeclampsia", d: "Placenta previa" },
    answer: "c",
  },
  {
    id: 36,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 37,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 38,
    question: "What is the normal fetal heart rate range?",
    options: { a: "110-160 bpm", b: "90-140 bpm", c: "120-170 bpm", d: "80-120 bpm" },
    answer: "a",
  },
  {
    id: 39,
    question: "Which vaccine is recommended during every pregnancy?",
    options: { a: "MMR", b: "Varicella", c: "Tdap", d: "Hepatitis B" },
    answer: "c",
  },
  {
    id: 40,
    question: "What condition is characterized by high blood pressure and protein in the urine during pregnancy?",
    options: { a: "Eclampsia", b: "Gestational diabetes", c: "Preeclampsia", d: "Placenta previa" },
    answer: "c",
  },
  {
    id: 41,
    question: "Which stage of labor involves full cervical dilation?",
    options: { a: "First stage", b: "Second stage", c: "Third stage", d: "Latent stage" },
    answer: "b",
  },
  {
    id: 42,
    question: "Which hormone is primarily responsible for maintaining pregnancy?",
    options: { a: "Estrogen", b: "Progesterone", c: "Oxytocin", d: "Prolactin" },
    answer: "b",
  },
  {
    id: 43,
    question: "What condition is characterized by high blood pressure and protein in the urine during pregnancy?",
    options: { a: "Eclampsia", b: "Gestational diabetes", c: "Preeclampsia", d: "Placenta previa" },
    answer: "c",
  },
  {
    id: 44,
    question: "Which is a common sign of labor?",
    options: { a: "Weight gain", b: "Breast tenderness", c: "Regular uterine contractions", d: "Increased appetite" },
    answer: "c",
  },
  {
    id: 45,
    question: "What is the normal duration of human pregnancy?",
    options: { a: "38 weeks", b: "40 weeks", c: "42 weeks", d: "36 weeks" },
    answer: "b",
  },
  {
    id: 46,
    question: "What is the normal duration of human pregnancy?",
    options: { a: "38 weeks", b: "40 weeks", c: "42 weeks", d: "36 weeks" },
    answer: "b",
  },
  {
    id: 47,
    question: "Which hormone is primarily responsible for maintaining pregnancy?",
    options: { a: "Estrogen", b: "Progesterone", c: "Oxytocin", d: "Prolactin" },
    answer: "b",
  },
  {
    id: 48,
    question: "Which vitamin is essential to prevent neural tube defects during pregnancy?",
    options: { a: "Vitamin A", b: "Vitamin B12", c: "Folic Acid", d: "Vitamin D" },
    answer: "c",
  },
  {
    id: 49,
    question: "Which vitamin is essential to prevent neural tube defects during pregnancy?",
    options: { a: "Vitamin A", b: "Vitamin B12", c: "Folic Acid", d: "Vitamin D" },
    answer: "c",
  },
  {
    id: 50,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 51,
    question: "Which stage of labor involves full cervical dilation?",
    options: { a: "First stage", b: "Second stage", c: "Third stage", d: "Latent stage" },
    answer: "b",
  },
  {
    id: 52,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 53,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 54,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 55,
    question: "Which stage of labor involves full cervical dilation?",
    options: { a: "First stage", b: "Second stage", c: "Third stage", d: "Latent stage" },
    answer: "b",
  },
  {
    id: 56,
    question: "Which vaccine is recommended during every pregnancy?",
    options: { a: "MMR", b: "Varicella", c: "Tdap", d: "Hepatitis B" },
    answer: "c",
  },
  {
    id: 57,
    question: "Which is a common sign of labor?",
    options: { a: "Weight gain", b: "Breast tenderness", c: "Regular uterine contractions", d: "Increased appetite" },
    answer: "c",
  },
  {
    id: 58,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 59,
    question: "Which stage of labor involves full cervical dilation?",
    options: { a: "First stage", b: "Second stage", c: "Third stage", d: "Latent stage" },
    answer: "b",
  },
  {
    id: 60,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 61,
    question: "Which stage of labor involves full cervical dilation?",
    options: { a: "First stage", b: "Second stage", c: "Third stage", d: "Latent stage" },
    answer: "b",
  },
  {
    id: 62,
    question: "Which is a common sign of labor?",
    options: { a: "Weight gain", b: "Breast tenderness", c: "Regular uterine contractions", d: "Increased appetite" },
    answer: "c",
  },
  {
    id: 63,
    question: "Which vitamin is essential to prevent neural tube defects during pregnancy?",
    options: { a: "Vitamin A", b: "Vitamin B12", c: "Folic Acid", d: "Vitamin D" },
    answer: "c",
  },
  {
    id: 64,
    question: "Which is a common sign of labor?",
    options: { a: "Weight gain", b: "Breast tenderness", c: "Regular uterine contractions", d: "Increased appetite" },
    answer: "c",
  },
  {
    id: 65,
    question: "Which vaccine is recommended during every pregnancy?",
    options: { a: "MMR", b: "Varicella", c: "Tdap", d: "Hepatitis B" },
    answer: "c",
  },
  {
    id: 66,
    question: "What is the normal duration of human pregnancy?",
    options: { a: "38 weeks", b: "40 weeks", c: "42 weeks", d: "36 weeks" },
    answer: "b",
  },
  {
    id: 67,
    question: "What is the normal duration of human pregnancy?",
    options: { a: "38 weeks", b: "40 weeks", c: "42 weeks", d: "36 weeks" },
    answer: "b",
  },
  {
    id: 68,
    question: "Which stage of labor involves full cervical dilation?",
    options: { a: "First stage", b: "Second stage", c: "Third stage", d: "Latent stage" },
    answer: "b",
  },
  {
    id: 69,
    question: "What is the normal duration of human pregnancy?",
    options: { a: "38 weeks", b: "40 weeks", c: "42 weeks", d: "36 weeks" },
    answer: "b",
  },
  {
    id: 70,
    question: "What condition is characterized by high blood pressure and protein in the urine during pregnancy?",
    options: { a: "Eclampsia", b: "Gestational diabetes", c: "Preeclampsia", d: "Placenta previa" },
    answer: "c",
  },
  {
    id: 71,
    question: "Which is a common sign of labor?",
    options: { a: "Weight gain", b: "Breast tenderness", c: "Regular uterine contractions", d: "Increased appetite" },
    answer: "c",
  },
  {
    id: 72,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 73,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 74,
    question: "What condition is characterized by high blood pressure and protein in the urine during pregnancy?",
    options: { a: "Eclampsia", b: "Gestational diabetes", c: "Preeclampsia", d: "Placenta previa" },
    answer: "c",
  },
  {
    id: 75,
    question: "Which vaccine is recommended during every pregnancy?",
    options: { a: "MMR", b: "Varicella", c: "Tdap", d: "Hepatitis B" },
    answer: "c",
  },
  {
    id: 76,
    question: "Which hormone is primarily responsible for maintaining pregnancy?",
    options: { a: "Estrogen", b: "Progesterone", c: "Oxytocin", d: "Prolactin" },
    answer: "b",
  },
  {
    id: 77,
    question: "Which is a common sign of labor?",
    options: { a: "Weight gain", b: "Breast tenderness", c: "Regular uterine contractions", d: "Increased appetite" },
    answer: "c",
  },
  {
    id: 78,
    question: "What condition is characterized by high blood pressure and protein in the urine during pregnancy?",
    options: { a: "Eclampsia", b: "Gestational diabetes", c: "Preeclampsia", d: "Placenta previa" },
    answer: "c",
  },
  {
    id: 79,
    question: "Which hormone is primarily responsible for maintaining pregnancy?",
    options: { a: "Estrogen", b: "Progesterone", c: "Oxytocin", d: "Prolactin" },
    answer: "b",
  },
  {
    id: 80,
    question: "Which vitamin is essential to prevent neural tube defects during pregnancy?",
    options: { a: "Vitamin A", b: "Vitamin B12", c: "Folic Acid", d: "Vitamin D" },
    answer: "c",
  },
  {
    id: 81,
    question: "What is the normal duration of human pregnancy?",
    options: { a: "38 weeks", b: "40 weeks", c: "42 weeks", d: "36 weeks" },
    answer: "b",
  },
  {
    id: 82,
    question: "What is the normal duration of human pregnancy?",
    options: { a: "38 weeks", b: "40 weeks", c: "42 weeks", d: "36 weeks" },
    answer: "b",
  },
  {
    id: 83,
    question: "Which vaccine is recommended during every pregnancy?",
    options: { a: "MMR", b: "Varicella", c: "Tdap", d: "Hepatitis B" },
    answer: "c",
  },
  {
    id: 84,
    question: "Which vaccine is recommended during every pregnancy?",
    options: { a: "MMR", b: "Varicella", c: "Tdap", d: "Hepatitis B" },
    answer: "c",
  },
  {
    id: 85,
    question: "What is the normal fetal heart rate range?",
    options: { a: "110-160 bpm", b: "90-140 bpm", c: "120-170 bpm", d: "80-120 bpm" },
    answer: "a",
  },
  {
    id: 86,
    question: "Which vitamin is essential to prevent neural tube defects during pregnancy?",
    options: { a: "Vitamin A", b: "Vitamin B12", c: "Folic Acid", d: "Vitamin D" },
    answer: "c",
  },
  {
    id: 87,
    question: "Which stage of labor involves full cervical dilation?",
    options: { a: "First stage", b: "Second stage", c: "Third stage", d: "Latent stage" },
    answer: "b",
  },
  {
    id: 88,
    question: "What is the normal fetal heart rate range?",
    options: { a: "110-160 bpm", b: "90-140 bpm", c: "120-170 bpm", d: "80-120 bpm" },
    answer: "a",
  },
  {
    id: 89,
    question: "Which stage of labor involves full cervical dilation?",
    options: { a: "First stage", b: "Second stage", c: "Third stage", d: "Latent stage" },
    answer: "b",
  },
  {
    id: 90,
    question: "What is the normal fetal heart rate range?",
    options: { a: "110-160 bpm", b: "90-140 bpm", c: "120-170 bpm", d: "80-120 bpm" },
    answer: "a",
  },
  {
    id: 91,
    question: "What is the normal duration of human pregnancy?",
    options: { a: "38 weeks", b: "40 weeks", c: "42 weeks", d: "36 weeks" },
    answer: "b",
  },
  {
    id: 92,
    question: "What is the normal duration of human pregnancy?",
    options: { a: "38 weeks", b: "40 weeks", c: "42 weeks", d: "36 weeks" },
    answer: "b",
  },
  {
    id: 93,
    question: "What is the most common cause of postpartum hemorrhage?",
    options: { a: "Retained placenta", b: "Uterine atony", c: "Cervical tear", d: "Vaginal laceration" },
    answer: "b",
  },
  {
    id: 94,
    question: "Which vaccine is recommended during every pregnancy?",
    options: { a: "MMR", b: "Varicella", c: "Tdap", d: "Hepatitis B" },
    answer: "c",
  },
  {
    id: 95,
    question: "Which is a common sign of labor?",
    options: { a: "Weight gain", b: "Breast tenderness", c: "Regular uterine contractions", d: "Increased appetite" },
    answer: "c",
  },
  {
    id: 96,
    question: "Which is a common sign of labor?",
    options: { a: "Weight gain", b: "Breast tenderness", c: "Regular uterine contractions", d: "Increased appetite" },
    answer: "c",
  },
  {
    id: 97,
    question: "What is the primary purpose of prenatal care?",
    options: { a: "To detect fetal abnormalities", b: "To provide genetic counseling", c: "To monitor the health of mother and fetus", d: "To prepare for delivery only" },
    answer: "c",
  },
  {
    id: 98,
    question: "Which vitamin is essential to prevent neural tube defects during pregnancy?",
    options: { a: "Vitamin A", b: "Vitamin B12", c: "Folic Acid", d: "Vitamin D" },
    answer: "c",
  },
  {
    id: 99,
    question: "Which hormone is primarily responsible for maintaining pregnancy?",
    options: { a: "Estrogen", b: "Progesterone", c: "Oxytocin", d: "Prolactin" },
    answer: "b",
  },
  {
    id: 100,
    question: "What is the normal duration of human pregnancy?",
    options: { a: "38 weeks", b: "40 weeks", c: "42 weeks", d: "36 weeks" },
    answer: "b",
  },
];

    